# Generated by Django 3.1.2 on 2020-10-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20201026_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='student_attempt_question',
        ),
    ]
