# Generated by Django 3.1.2 on 2020-11-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_socialdistantvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdistantvideo',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
